/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin.employee;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author pande
 */
public class EditEmployeeDet extends javax.swing.JPanel {
    Object [] row;
    DefaultTableModel model;

    /**
     * Creates new form ViewAllEmployee
     */
    public EditEmployeeDet() {
        
        
        initComponents();
        getEmployee();
    }
    
    
    void getEmployee(){
        model = (DefaultTableModel) jTable.getModel();
        String name,email;
        int srno = 0;
        try{
            ResultSet rs = dbconnection.Db_Operations.showAllEmployee();
            if(rs!=null){
                while(rs.next()){
                    srno += 1;
                    name = rs.getString("name");
                    email = rs.getString("email");
                    
                    row=new Object[]{srno,name,email};
                    model.addRow(row);
//                    System.out.println(name+" : "+email);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelMouseEffect1 = new admin.form.PanelMouseEffect();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        panelMouseEffect1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr no.", "Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        panelMouseEffect1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 660));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, 30));

        jTextField2.setEditable(false);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 230, 30));

        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 230, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, 30));

        jButton1.setFont(new java.awt.Font("Hack Nerd Font", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 100, 40));

        jButton2.setFont(new java.awt.Font("Hack Nerd Font", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 90, 40));

        jLabel1.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 50, -1));

        jLabel2.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 60, -1));

        jLabel3.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 50, -1));

        jLabel5.setFont(new java.awt.Font("Hack Nerd Font", 0, 12)); // NOI18N
        jLabel5.setText("Phone No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        panelMouseEffect1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 540, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMouseEffect1, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMouseEffect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int row = jTable.getSelectedRow();
        String email = (String)jTable.getValueAt(row, 2);
        ResultSet rs = dbconnection.Db_Operations.getSelectedEmployee(email);
        try{
            if(rs!=null){
                if(rs.next()){
                    jTextField1.setText(rs.getString("name"));
                    jTextField2.setText(rs.getString("email"));
                    jTextField3.setText(rs.getString("password"));
                    jTextField4.setText(rs.getString("phone_no"));
                    String gender = rs.getString("gender");
                    if(gender.equals("M")){
                        jRadioButton1.setSelected(true);
                    }
                else{
                      jRadioButton2.setSelected(true);
                    }
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        System.out.println(email);
    }//GEN-LAST:event_jTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText();
        String email = jTextField2.getText();
        String pass = jTextField3.getText();
        String phone = jTextField4.getText();
        String gender = "";
        if(jRadioButton1.isSelected()){
            gender = "M";
        }else{
            gender = "F";
        }
        int i = dbconnection.Db_Operations.UpdateEmployeeDetails(name, email, phone, gender, pass);
        if(i>0) 
        {    
            JOptionPane.showMessageDialog(this, "Values updated Successfully");
            new admin.main.AdminPanel().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "An Error Occured","Update Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String email = jTextField2.getText();
        int i = dbconnection.Db_Operations.DeleteEmployee(email);
        if(i>0) 
        {    
            JOptionPane.showMessageDialog(this, "deleted Successfully");
            new admin.main.AdminPanel().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "An Error Occured","Update Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private admin.form.PanelMouseEffect panelMouseEffect1;
    // End of variables declaration//GEN-END:variables
}
