/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin.employee;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author pande
 */
public class ViewAllEmployee extends javax.swing.JPanel {
    Object [] row;
    DefaultTableModel model;

    /**
     * Creates new form ViewAllEmployee
     */
    public ViewAllEmployee() {
        
        
        initComponents();
        getEmployee();
    }
    
    
    void getEmployee(){
        model = (DefaultTableModel) jTable.getModel();
        String name,email;
        int srno = 0;
        try{
            ResultSet rs = dbconnection.Db_Operations.showAllEmployee();
            if(rs!=null){
                while(rs.next()){
                    srno += 1;
                    name = rs.getString("name");
                    email = rs.getString("email");
                    
                    row=new Object[]{srno,name,email};
                    model.addRow(row);
                    System.out.println(name+" : "+email);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMouseEffect1 = new admin.form.PanelMouseEffect();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        panelMouseEffect1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr no.", "Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        panelMouseEffect1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMouseEffect1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMouseEffect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private admin.form.PanelMouseEffect panelMouseEffect1;
    // End of variables declaration//GEN-END:variables
}
